[package]
name = "pardon-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
anyhow.workspace = true
log.workspace = true
notify-rust.workspace = true
tokio = { workspace = true, features = ["process"] }
base64.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile = "3"
